Update
ciena-blueplanet/ember-dagre pull request #80
Opened 2017-06-20 19:22 UTC by helloWorldCindy

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

Upgrade Ember CLI version from 2.11.0 to 2.12.3

2017-06-21 00:14 UTC, juwara0 commented
DO NOT MERGE - This is still being worked on

2017-06-21 15:42 UTC, juwara0 commented on .npmignore
>  .eslintrc
We can remove the `.eslintrc` entry as well as the `.eslintrc` file.

2017-06-22 14:59 UTC, notmessenger requested changes

2017-06-22 14:59 UTC, notmessenger commented on .eslintrc.js
> +module.exports = {
This files content should only be:

```
/* eslint-env node */

module.exports = {
  extends: 'frost-standard',
}
```

2017-06-22 14:59 UTC, notmessenger commented on .npmignore
> +.eslintrc.js
Remove this duplicate entry

2017-06-22 14:59 UTC, notmessenger commented on .travis.yml
> +  - node_js: 'stable'
This entry, and section, does not match https://github.com/ciena-frost/ember-frost-test/blob/master/.travis.yml, for example.  @juwara0 how/when are we handling the standardization of these configurations?  At the very least I'd rather not be introducing this change even if we're not going to remove the entire section for standardization (if that is the action we decided to take)

2017-06-22 14:59 UTC, notmessenger commented on ember-cli-build.js
>  var EmberAddon = require('ember-cli/lib/broccoli/ember-addon')
This line should be changed to

`const EmberAddon = require('ember-cli/lib/broccoli/ember-addon')`

2017-06-22 14:59 UTC, notmessenger commented on .npmignore
>  .jshintrc
Remove this entry

2017-06-22 14:59 UTC, notmessenger commented on .eslintrc
> -    "URL": false
Determine whether the global `URL` value needs to be added to the _.eslintrc.js_ file

2017-06-22 15:00 UTC, notmessenger commented
- The contents of the _tests/helpers/start-app.js_ file need to be changed to:

```
import Ember from 'ember'
const {merge, run} = Ember

import Application from '../../app'
import config from '../../config/environment'

export default function startApp (attrs) {
  let attributes = merge({}, config.APP)
  attributes = merge(attributes, attrs) // use defaults, but you can override;

  return run(() => {
    let application = Application.create(attributes)
    application.setupForTesting()
    application.injectTestHelpers()
    return application
  })
}
```

- The _tests/.eslintrc_ file needs to be deleted

- the `ember-cli-app-version` dependency should be removed from `package.json`

- the `ember-cli-test-loader` dependency should be removed from _package.json_

- should set the `broccoli-asset-rev` dependency in _package.json_ to `^2.4.5` so that we're in alignment with the value from ember-cli@2.12.3 and the other repos being set to the same

- should set the `ember-cli-inject-live-reload` dependency in _package.json_ to `^1.4.1` so that we're in alignment with the value from ember-cli@2.12.3 and the other repos being set to the same

- should set the `ember-export-application-global` dependency in _package.json_ to `^1.0.5` so that we're in alignment with the value from ember-cli@2.12.3 and the other repos being set to the same

- should set the `ember-load-initializers` dependency in _package.json_ to `^0.6.0` so that we're in alignment with the value from ember-cli@2.12.3 and the other repos being set to the same

2017-06-22 15:16 UTC, helloWorldCindy commented on .travis.yml
> +  - node_js: 'stable'
Should I changed it to be the same as the one in  https://github.com/ciena-frost/ember-frost-test/blob/master/.travis.yml ? But the builds are failing with Node.js: stable

2017-07-07 14:42 UTC, dafortin commented on .travis.yml
> +     - env: EMBER_TRY_SCENARIO=ember-release
We should remove this. It's not necessary. 

You will need to allow failures on:
```
- node_js: 'stable'
```

2017-07-07 14:43 UTC, dafortin commented on .travis.yml
> +     - env: EMBER_TRY_SCENARIO=ember-release
`gallow_failures`. I though that It should be `allow_failures`.

2017-07-07 14:46 UTC, dafortin commented on package.json
> +    "loader.js": "^4.2.3"
`ember-cli-babel` should be `^5.1.7`

2017-07-07 17:18 UTC, helloWorldCindy commented on .travis.yml
> +     - env: EMBER_TRY_SCENARIO=ember-release
Fixed.

2017-07-07 17:18 UTC, helloWorldCindy commented on package.json
> +    "loader.js": "^4.2.3"
Fixed.

2017-07-07 18:52 UTC, notmessenger commented
The `http` in the _.gitignore_ file should be `https`

2017-07-07 18:54 UTC, notmessenger requested changes

2017-07-07 18:54 UTC, notmessenger commented on .travis.yml
> +
Are we adding empty spaces here or  just an empty row?  The diff makes it look like spaces.

2017-07-07 18:54 UTC, notmessenger commented on tests/.eslintrc.js
> +};
Remove `;`

2017-07-07 18:54 UTC, notmessenger commented on tests/dummy/config/environment.js
>  module.exports = function (environment) {
Set `locationType` to `hash`

2017-07-07 19:07 UTC, juwara0 commented on tests/dummy/config/environment.js
>  module.exports = function (environment) {
Fixed

2017-07-10 16:29 UTC, notmessenger approved these changes

2017-07-10 16:30 UTC, notmessenger commented
👍

2017-07-10 16:30 UTC, merged